# Generated by Django 5.2.9 on 2025-12-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
