# Generated by Django 5.2.9 on 2025-12-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_reset_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
