# Generated by Django 5.2.9 on 2026-01-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('Founder/Co-founder', 'Founder/Co-founder'), ('CA (Chartered Accountant)', 'CA (Chartered Accountant)'), ('CS (Company Secretary)', 'CS (Company Secretary)'), ('Legal', 'Legal'), ('Firm', 'Firm')], max_length=50),
        ),
    ]
